class_name Enumerations
extends Node

enum REELSTATE{READY, SPINNING, STOPPING, STOPPED, SKIPPED}
enum SLOTSTATE{READY, SPIN_BEGIN, SPINNING, STOPPING, SKIPPED, SHOW_WIN, MINI_GAME, STOPPED}
enum GAMESTATE{DEFAULT, TRANSITIONING, BONUSGAME1, BONUSGAME2, GAMBLE}
enum SPINBUTTONTYPE{SPIN, STOP, AUTOPLAY}
enum SERVERERROR{INSUFFICIENT_FUNDS, LOST_CONNECTION, AUTHENTICATION_ERROR}
enum POPUPTYPES{INFORMATION, ERROR}
enum AUDIOCHANNEL{MASTER, MUSIC, SOUND, BGM, AMBIENCE, BIGWINS, SETTLEMENT, SPIN, WIN, SYMBOL, SYMBOL_STATIC, SYMBOL_WILD, SYMBOL_SCATTER, SYMBOL_SCATTER_BASE, SYMBOL_SCATTER_BONUS1, SYMBOL_SCATTER_BONUS2}
enum ENVIRONMENTSEQUENCE{WILD_LIGHTS, PRISONER_ON_WINDOW, HELICOPTER,
		SIRENS, SIRENS_ANTICIPATION, CLOUD, ANTICIPATION_REEL, ANTICIPATION_SPOTLIGHTS}
enum DISPLAYMODE{UNDEFINED, DESKTOP, MOBILE_LANDSCAPE, MOBILE_PORTRAIT}

enum AUTOPLAYRULES{WIN_LIMIT, SINGLE_WIN_LIMIT, LOSE_LIMIT, BONUS_PLAY, BIG_WIN, MAX_WIN, DECREASE_ON_BONUS}

# Need to be updated as the HTML Panels changed/updated
enum HTMLPANEL{OPEN_INFO, OPEN_PAYTABLE, OPEN_HISTORY, OPEN_AUDIO_SETTINGS, 
		OPEN_AUTOPLAY, OPEN_REPLAY_START, OPEN_REPLAY_END, OPEN_ERROR_PANEL, CLOSE_ERROR_PANEL, DIRECT_TO_LOBBY,
		SET_LANGUAGE, SET_MUSIC_LEVEL, SET_SFX_LEVEL, SET_SESSION, SET_DEFAULTS,
		AUTOPLAY_START, REPLAY_START, QUICK_SPIN, BONUS_FEATURE_WON, SET_VOLUME, BUTTON_CLICKED}
		
enum NETWORK_REQUEST { CONFIG, MOCK_CASINO_SESSION, MOCK_CASINO_TOKEN, LOGIN, INFOS, ROUND, LOCALIZATION, SHARE_ROUND, REPLAY, GAME_INFO, PLAYER_PREFERENCES, EXTEND_SESSION, PING}

const AnticipationFX = "AnticipationFX"

